config/routes.rb
Rails.application.routes.draw do
  
  resources :yoga_classes do 
    resources :students
  end 

  resources :studios, only: [:index, :show]
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'callbacks'}

  # root to: 'application#welcome'
  devise_scope :user do 
    authenticated :user do
      root 'application#welcome', as: :authenticated_root
    end 

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    get 'login', to: 'devise/sessions#new', as: 'login'
    get 'signup', to: 'devise/registrations#new', as: 'signup'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :yoga_class
    validates :name, presence: true
end

app/models/studio.rb
class Studio < ApplicationRecord
    has_many :yoga_classes 
    has_many :users, through: :yoga_classes 
    validates :name, presence: true
    validates :address, presence: true
    validates :phone_number, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :yoga_classes
  has_many :studios, through: :yoga_classes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.username = auth.info.name 
            user.uid = auth.uid 
            user.email = auth.info.email 
            user.password = Devise.friendly_token[0,20]
        end 
    end 

end

app/models/yoga_class.rb
class YogaClass < ApplicationRecord
    belongs_to :studio
    belongs_to :user
    has_many :students
    validates :name, presence: true
    validates :length, presence: true
    validates :difficulty, presence: true
    validates :date, presence: true
    validates :time, presence: true
    validates :studio, presence: true
    accepts_nested_attributes_for :studio, reject_if: :all_blank
    scope :future_classes, -> { where('date >= ?', Date.today) }
    scope :past_classes, -> { where('date < ?', Date.today) }
    
    DIFFICULTY_LIST = ["Beginner", "Intermediate", "Advanced", "All Levels"]

    def yoga_class_date
        self.date.strftime('%A, %B %d, %Y')
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    
    def github
        
        @user = User.from_omniauth(request.env["omniauth.auth"])
        # binding.pry 
        sign_in_and_redirect @user
    end 

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    # private

    # def signup_params
    #     params.require(:user).permit(:username, :email, :password, :password_confirmation)
    # end 

    # def account_update_params
    #     params.require(:user).permit(:username, :email, :password, :password_confirmation)
    # end 

    before_action :configure_permitted_parameters, if: :devise_controller? 
    
    protected 
    def configure_permitted_parameters    
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])  
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_yoga_class
  before_action :set_student, only: [:update, :destroy]
    
    def index  
      @students = @yoga_class.students.find_by(id: params[:yoga_class_id])
    end   
  
    def new 
      if params[:yoga_class_id] && !YogaClass.exists?(params[:yoga_class_id])
        redirect_to yoga_classes_path, alert: "Yoga class not found."
      else 
         @student = @yoga_class.students.build(yoga_class_id: params[:yoga_class_id])
      end 
    end
    
    def create
      @student = @yoga_class.students.new(student_params)
        if @student.valid?
          @student.save
          redirect_to yoga_class_student_path(@yoga_class, @student)
        else 
          render :new
        end 
    end

    def show 
      if @yoga_class.nil?
        redirect_to yoga_classes_path, alert: "Yoga class not found."
      else set_student 
        if 
          @student.nil?
          redirect_to yoga_class_path(@yoga_class), alert: "Student not found."
        end 
      end 
    end 
    
    def edit 
      if @yoga_class.nil?
        redirect_to yoga_classes_path, alert: "Yoga class not found."
      else set_student 
        if @student.nil?
        redirect_to yoga_class_path(@yoga_class), alert: "Student not found."
        end 
      end 
    end 

    def update
      if @student.update(student_params)
        redirect_to yoga_class_student_path(@yoga_class, @student)
      else 
        render :edit
      end 
    end 

    def destroy
      @student.destroy 
      flash[:notice] = "Student deleted."
      redirect_to yoga_class_path(@student.yoga_class)
    end


      private

        def set_yoga_class
          @yoga_class = YogaClass.find_by(id: params[:yoga_class_id])
        end 

        def set_student
          @student = @yoga_class.students.find_by(id: params[:id])
        end 

        def student_params
            params.require(:student).permit(:name, :yoga_class_id)
        end 

end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController

    def index
      @studios = current_user.studios.uniq
    end
    
    def show 
       @studio = current_user.studios.find_by(id: params[:id])
        if @studio.nil?
          redirect_to studios_path, alert: "Studio not found."
        end 
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/yoga_classes_controller.rb
class YogaClassesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_yoga_class, only: [:show, :edit, :update, :destroy]

  def index
    if params[:past_classes]
      @past_yoga_classes = current_user.yoga_classes.past_classes
      @past_yoga_classes = @past_yoga_classes.order(date: :asc)
    end 
    @yoga_classes = current_user.yoga_classes.future_classes
    @yoga_classes = @yoga_classes.order(date: :asc)
  end

  def new
    @yoga_class = current_user.yoga_classes.build
     
  end

  def create
    @yoga_class = current_user.yoga_classes.new(yoga_class_params)
      if @yoga_class.valid?
        @yoga_class.save
        redirect_to yoga_class_path(@yoga_class) 
      else 
        render :new
      end 
  end

  def show 
    if @yoga_class.nil?
      redirect_to yoga_classes_path, alert: "Yoga class not found."
    end 
  end 

  def edit
    if @yoga_class.nil?
      redirect_to yoga_classes_path, alert: "Yoga class not found."
    end 
  end

  def update
      if @yoga_class.update(yoga_class_params)
        redirect_to yoga_class_path(@yoga_class) 
      else 
        render :new
      end 
  end

  def destroy
    @yoga_class.destroy 
    flash[:notice] = "Yoga class deleted."
    redirect_to yoga_classes_path
  end

  private

    def set_yoga_class
      @yoga_class = current_user.yoga_classes.find_by(id: params[:id])
    end 

    def yoga_class_params
      # raise params.inspect 
      params.require(:yoga_class).permit(:user_id, :name, :length, :date, :time, :difficulty, :past_classes, :studio_id, studio_attributes: [:name, :address, :phone_number])
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/yoga_classes_helper.rb
module YogaClassesHelper
end 

app/views/application/welcome.html.erb
<% if user_signed_in? %>
<div class="container-fluid text-center">
<%= link_to "Yoga Class Index", yoga_classes_path %><br>
<%= link_to "Studio Index", studios_path %>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <li class="navbar-brand">YogaOnRails</li>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <li class="nav-link"><%= link_to "Home", authenticated_root_path %><span class="sr-only">(current)</span></li>
      </li>
      <% if !user_signed_in? %>
        <li class="nav-item">
            <li class="nav-link"><%= link_to "Signup", signup_path %></li>
        </li>
    <% else %>
        <li class="nav-item">
            <li class="nav-link"><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
        </li>
        <li class="nav-item">
            <li class="nav-link"><%= current_user.username %></li>
        </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yoga_on_rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav>
    <%= render 'layouts/nav'%>
  </nav>

  <header>
  <% if user_signed_in? %>
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Welcome to YogaOnRails!</h1>
        <p>A space for yoga teachers to manage their classes and studios.</p>
      </div>
    </div>
  <% end %>
  </header>

  <body>
  <div class="container-fluid text-center">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for [@yoga_class, @student] do |f| %>

<% if @student.errors.any? %>
        <div id="error_explanation">
            <h2>
            <%= pluralize(@student.errors.count, "error") %>
            prohibited this student from being saved:
            </h2>
 
        <ul>
            <% @student.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

<%= f.label :name %>
<%= f.hidden_field :yoga_class_id %>
<%= f.text_field :name %><br></br>
<%= f.submit "Submit", class: "btn btn-large btn-primary"  %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>
<br></br>

<%= link_to "Back to Class Details", yoga_class_path(@yoga_class) %><br>
<%= link_to "Back to Yoga Class Index", yoga_classes_path %>

app/views/students/index.html.erb
<h3>Students signed up for <%= @yoga_class.name %>:</h3>

    <% @yoga_class.students.each do |student| %>
    <p><%= link_to student.name, yoga_class_student_path(@yoga_class, student) %><br>
<% end %>
<br></br>


<%= link_to "Back to Class Details", yoga_class_path(@yoga_class) %><br>
<%= link_to "Back to Class Index", yoga_classes_path %>

app/views/students/new.html.erb
<h3>Add Student</h3>

<%= render 'form' %>
<br></br>
<%= link_to "Back to Class Details", yoga_class_path(@yoga_class) %><br>
<%= link_to "Back to Yoga Class Index", yoga_classes_path %>

app/views/students/show.html.erb
<h3>New Student Added:</h3>
<p><%= @student.name %></p>
<p>is signed up for <%= @student.yoga_class.name %>
(<%= link_to "Edit Student", edit_yoga_class_student_path(@student.yoga_class, @student) if @student.yoga_class %>)</p>
<br></br>

<%= link_to "Delete Student", { action: :destroy, id: @student.id }, method: :delete, data: { confirm: 'Are you sure?' } %><br>
<%= link_to "Back to Class Details", yoga_class_path(@yoga_class) %><br>
<%= link_to "Back to Class Index", yoga_classes_path %><br>

app/views/studios/index.html.erb
<h3><%= current_user.username %>'s Studios </h3>

<% @studios.each do |s| %>
<%= link_to s.name, studio_path(s) %><br>
<% end %>

<br></br>

<%= link_to "Yoga Class Index", yoga_classes_path %>

app/views/studios/show.html.erb
<h3><%= @studio.name %></h3>

<p>Address: <%= @studio.address %></p>
<p>Phone Number: <%= @studio.phone_number %></p>

<h4>Classes at this Studio: </h4>
<% @studio.yoga_classes.each do |y| %>
<li>
<%= y.length%> minute <%= y.name %> with <%= y.user.username %>
</li>
<% end %>
<br></br>
<%= link_to "Back to Studio Index", studios_path %>

app/views/yoga_classes/_form.html.erb
<%= form_for @yoga_class do |f| %>

    <% if @yoga_class.errors.any? %>
        <div id="error_explanation">
            <h2>
            <%= pluralize(@yoga_class.errors.count, "error") %>
            prohibited this yoga class from being saved:
            </h2>
 
        <ul>
            <% @yoga_class.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :length%>
<%= f.text_field :length %><br>
<%= f.label :difficulty%>
<%= f.select(:difficulty, YogaClass::DIFFICULTY_LIST )%><br>
<%= f.label :date%>
<%= f.date_field :date %><br>
<%= f.label :time %>
<%= f.time_field :time %><br>
<%= f.label "Select a Studio" %>
<%= f.collection_select :studio_id, current_user.studios.all.uniq, :id, :name, {:include_blank => "Please select"} %><br>

<h3>Or Add a New Studio:</h3>
<%= f.fields_for :studio, @yoga_class.build_studio do |studio| %>
    <%= studio.label :name %>
    <%= studio.text_field :name %><br>
    <%= studio.label :address %>
    <%= studio.text_field :address %><br>
    <%= studio.label :phone_number %>
    <%= studio.text_field :phone_number %><br>
    <% end %>

<%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

app/views/yoga_classes/edit.html.erb
<h1>YogaClasses#edit</h1>
<p>Find me in app/views/yoga_classes/edit.html.erb</p>

app/views/yoga_classes/index.html.erb
<% if @past_yoga_classes %>
<h1>Past Yoga Classes</h1>
<hr>
    <% @past_yoga_classes.group_by(&:yoga_class_date).each do |yoga_class_date, yoga_class| %>
    <p class="font-weight-bold"><%= yoga_class_date %></p>
        <% yoga_class.each do |p| %>
        <%= link_to p.name, yoga_class_path(p) %><br>
    <% end %>
<% end %>
<% end %>
<br></br>

<h1>Upcoming Yoga Classes</h1>
<hr>
<% @yoga_classes.group_by(&:yoga_class_date).each do |yoga_class_date, yoga_class| %>
<div>
    <p class="font-weight-bold"><%= yoga_class_date %></p>
        <% yoga_class.each do |c| %>
        <%= link_to c.name, yoga_class_path(c) %><br>
    <% end %>
<% end %>
</div>
<br></br>

<div>
<%= button_to "Show Previous Classes", yoga_classes_path, method: :get, params: { past_classes: true }, class: "btn btn-outline-secondary"%><br>
<%= link_to "Add a class", new_yoga_class_path %><br>
<%= link_to "Studio Index", studios_path %>
</div>

app/views/yoga_classes/new.html.erb
<h1>Add a new class</h1>

<%= render 'form' %>

<br></br>
<%= link_to "Back to Yoga Class Index", yoga_classes_path %>

app/views/yoga_classes/show.html.erb
<h3><%= @yoga_class.length%> minute <%= @yoga_class.name %> with <%= @yoga_class.user.username %></h3>
<p>Date: <%= @yoga_class.date %></p>
<p>Time: <%= @yoga_class.time %></p>
<p>Studio: <%= @yoga_class.studio.name %></p>
<p>Level: <%= @yoga_class.difficulty %></p><br>

<br>

<% if @yoga_class.students.any?%>
    <h3><%= link_to "Students", yoga_class_students_path(@yoga_class) %></h3>
    <% @yoga_class.students.each do |student| %>
    <%= link_to student.name, yoga_class_student_path(@yoga_class, student) %><br>
    <% end %>
<br></br>
<% end %>

<%= link_to "Add Student", new_yoga_class_student_path(@yoga_class) %><br>
<%= link_to "Delete Class", { action: :destroy, id: @yoga_class.id }, method: :delete, data: { confirm: 'Are you sure?' } %><br>
<%= link_to "Edit Class", edit_yoga_class_path(@yoga_class) %><br>
<%= link_to "Back to Class Index", yoga_classes_path %><br>